mpi:
  - nompi
  - mpich
  - openmpi
# This is to make sure "mpi" above is *NOT* used to compute the package hash. For "cutensornet"
# the non-colliding hashes are acceptable (though not preferred if avoidable) because we
# wanted 3 flavors of "cutensornet" generated. But, for the "cuquantum" metapackage if the
# hashes are not colliding we'd also generate 3 packages (one for each "mpi" flavor), despite
# it has nothing to do with MPI. We better make sure we have colliding hashes, so that only
# 1 unique upload would be done by the CI.
ignore_version:
  - mpi


docker_image:                                    # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
   - quay.io/condaforge/linux-anvil-cos7-x86_64  # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]

c_compiler_version:        # [linux]
  - 10                     # [linux64]

cxx_compiler_version:      # [linux]
  - 10                     # [linux64]

fortran_compiler_version:  # [linux]
  - 10                     # [linux64]

cuda_compiler:
  - cuda-nvcc

cuda_compiler_version:
  - 12.0

cudnn:
  - None

cdt_name:                  # [linux]
  - cos7                   # [linux64]
